packageExtensions:
  '@vue/test-utils@*':
    peerDependencies:
      '@vue/compiler-dom': '*'
      '@vue/server-renderer': '*'
  '@testing-library/vue@*':
    dependencies:
      '@vue/compiler-dom': '*'
      '@vue/server-renderer': '*'
