days = [ // month, day
  [4, 9, "banshtai tsai", "International Banshtai Tsai Day"],
  [5, 13, "hummus", "International Hummus Day"],
  [6, 1, "glass of milk", "World Milk Day"],
  [6, 21, "sushi platter", "International Sushi Day"],
  [7, 7, "chocolate bar", "World Chocolate Day"],
  [9, 5, "bacon", "International Bacon Day"],
  [9, 29, "cup of coffee", "International Coffee Day"],
  [10, 1, "vegetarian meal", "World Vegetarian Day"],
  [10, 2, "farm animal", "World Farm Animals Day"],
  [10, 9, "pizza and a beer", "International Beer and Pizza Day"],
  [10, 16, "meal of any kind", "World Food Day"],
  [11, 1, "vegan meal", "World Vegan Day"],
  [11, 17, "glass of happy gose", "International Happy Gose Day"],
  [10, 31, "secure source of food", "Africa Day for Food and Nutrition Security", "Africa"],
  [5, 28, "burger", "National Burger Day", "Australia"],
  [12, 18, "muffin", "National Muffin Day", "Brazil"],
  [6, 27, "bag of chips", "National Chip Day", "Canada"],
  [1, 11, "German apple", "German Apples Day", "Germany"],
  [4, 23, "German beer", "German Beer Day", "Germany"],
  [11, 25, "German butterbrot", "German Butterbrot Day", "Germany"],
  [4, 9, "bowl of soup", "National Soup Day", "Germany"],
  [3, 1, "glass of beer", "Beer Day", "Iceland"],
  [1, 14, "undhiyu", "National Undhiyu", "India"],
  [2, 29, "samosa", "World Samosa Day", "India"],
  [3, 30, "idli", "World Idli Day", "India"],
  [1, 23, "pie", "National Pie Day", "Iran"],
  [10, 27, "cheeseburger", "National Cheeseburger Day", "Iran"],
  [4, 17, "espresso", "National Espresso Day", "Italy"],
  [1, 5, "strawberry", "National Strawberry Day", "Japan"],
  [10, 10, "mochi cake", "National Mochi Day", "Japan"],
  [11, 11, "pocky stick", "National Pocky Day", "Japan"],
  [11, 11, "pepero stick", "National Pepero Day", "South Korea"],
  [3, 25, "waffle", "National Waffle Day", "Sweden"],
  [10, 4, "cinnamon bun", "National Cinnamon Bun Day", "Sweden"],
  [11, 7, "mud cake", "National Mud Cake Day", "Sweden"],
  [8, 9, "melon", "Melon Day", "Turkmenistan"],
  [1, 5, "sausage", "Sausage Day", "the UK"],
  [2, 28, "scouse", "National Scouse Day", "the UK"],
  [4, 7, "glass of beer", "National Beer Day", "the UK"],
  [6, 5, "fish and chips", "National Fish and Chips Day", "the UK"],
  [8, 27, "burger", "National Burger Day", "the UK"],
	[1, 2, "creampuff", "National Creampuff Day", "the US"],
	[1, 3, "chocolate-covered cherry", "National Chocolate Covered Cherry Day", "the US"],
	[1, 4, "cheese fondue", "National Cheese Fondue Day", "the US"],
	[1, 5, "bowl of whipped cream", "National Whipped Cream Day", "the US"],
	[1, 9, "cassoulet", "National Cassoulet Day", "the US"],
	[1, 19, "popcorn", "National Popcorn Day", "the US"],
	[1, 20, "slice of cheese", "Cheese Day", "the US"],
	[1, 22, "bottle of hot sauce", "National Hot Sauce Day", "the US"],
	[1, 23, "pie", "National Pie Day", "the US"],
	[1, 24, "jar of peanut butter", "National Peanut Butter Day", "the US"],
	[1, 27, "chocolate cake", "National Chocolate Cake Day", "the US"],
	[2, 2, "tater tot", "National Tater Tot Day", "the US"],
	[2, 9, "pizza", "National Pizza Day", "the US"],
	[2, 15, "butterscotch", "National I Want Butterscotch Day", "the US"],
	[2, 22, "margarita", "National Margarita Day", "the US"],
	[2, 23, "slice of banana bread", "National Banana Bread Day", "the US"],
	[2, 29, "frog leg", "National Frog Legs Day", "the US"],
	[3, 1, "jar of peanut butter", "National Peanut Butter Lover’s Day", "the US"],
	[3, 2, "banana creme pie", "National Banana Creme Pie Day", "the US"],
	[3, 3, "slice of Canadian bacon", "National Canadian Bacon Day", "the US"],
	[3, 5, "cheese doodle", "National Cheese Doodle Day", "the US"],
	[3, 7, "roast pork", "National Crown Roast of Pork Day", "the US"],
	[3, 8, "peanut butter cluster", "National Peanut Cluster Day", "the US"],
	[3, 9, "crab", "National Crabmeat Day", "the US"],
	[3, 9, "meatball", "National Meatball Day", "the US"],
	[3, 10, "blueberry popover", "National Blueberry Popover Day", "the US"],
	[3, 11, "oatmeal nut waffle", "Oatmeal Nut Waffles Day", "the US"],
	[3, 11, "apple", "Johnny Appleseed Day", "the US"],
	[3, 12, "scallop", "National Baked Scallops Day", "the US"],
	[3, 13, "coconut torte", "National Coconut Torte Day", "the US"],
	[3, 22, "corn dog", "National Corndog Day", "the US"],
	[3, 23, "bowl of chips with dip", "National Chips and Dip Day", "the US"],
	[3, 27, "glass of whiskey", "International Whiskey Day", "the US"],
	[3, 31, "clam on the half-shell", "National Clams on the Half Shell Day", "the US"],
	[3, 31, "bagel and cream cheese", "National Cream Cheese Frosting Day", "the US"],
	[4, 2, "PB&J", "National Peanut Butter and Jelly Day", "the US"],
	[4, 5, "caramel candy", "National Caramel Day", "the US"],
	[4, 7, "glass of beer", "National Beer Day", "the US"],
	[4, 11, "cheese fondue", "National Cheese Fondue Day", "the US"],
	[4, 12, "grilled cheese sandwich", "National Grilled Cheese Sandwich Day", "the US"],
	[4, 15, "banana", "National Banana Day", "the US"],
	[4, 17, "cheeseball", "National Cheeseball Day", "the US"],
	[4, 19, "clove of garlic", "National Garlic Day", "the US"],
	[4, 19, "rice ball", "National Rice Ball Day", "the US"],
	[4, 22, "jelly bean", "National Jellybean Day", "the US"],
	[4, 24, "pig in a blanket", "National Pigs in a Blanket Day", "the US"],
	[4, 25, "zucchini bread", "National Zucchini Bread Day", "the US"],
	[4, 26, "pretzel", "National Pretzel Day", "the US"],
	[4, 27, "prime rib", "National Prime Rib Day", "the US"],
	[4, 29, "shrimp scampi", "National Shrimp Scampi Day", "the US"],
	[5, 4, "candied orange peel", "National Candied Orange Peel Day", "the US"],
	[5, 5, "hoagie", "National Hoagie Day", "the US"],
	[5, 11, "whatever you fucking want", "National Eat What You Want Day", "the US"],
	[5, 17, "walnut", "National Walnut Day", "the US"],
	[5, 23, "taffy", "National Taffy Day", "the US"],
	[5, 24, "escargot", "National Escargot Day", "the US"],
	[5, 28, "brisket", "National Brisket Day", "the US"],
	[5, 28, "burger", "National Burger Day", "the US"],
	[6, 2, "rotisserie chicken", "National Rotisserie Chicken Day", "the US"],
	[6, 2, "rocky road ice cream", "National Rocky Road Day", "the US"],
	[6, 3, "chocolate macaroon", "National Chocolate Macaroon Day", "the US"],
	[6, 3, "egg", "National Egg Day", "the US"],
	[6, 4, "slice of cheese", "National Cheese Day", "the US"],
	[6, 4, "glass of cognac", "National Cognac Day", "the US"],
	[6, 5, "doughnut", "National Donut/Doughnut Day", "the US"],
	[6, 5, "gingerbread cookie", "National Gingerbread Day", "the US"],
	[6, 5, "glass of XXX moonshine", "National Moonshine Day", "the US"],
	[6, 6, "applesauce cake", "National Applesauce Cake Day", "the US"],
	[6, 7, "chocolate ice cream", "Chocolate Ice Cream Day", "the US"],
	[6, 10, "glass of iced tea", "National Iced Tea Day", "the US"],
	[6, 11, "corn on the cob", "National Corn on the Cob Day", "the US"],
	[6, 12, "peanut butter cookie", "National Peanut Butter Cookie Day", "the US"],
	[6, 15, "lobster", "National Lobster Day", "the US"],
	[6, 16, "fudge chocolate", "National Fudge Day", "the US"],
	[6, 17, "vegetable or two", "National Eat Your Vegetables Day", "the US"],
	[6, 20, "vanilla milkshake", "National Vanilla Milkshake Day", "the US"],
	[6, 20, "ice cream soda", "National Ice Cream Soda Day", "the US"],
	[6, 20, "kouign-amann", "National Kouign Amann Day", "the US"],
	[6, 21, "peaches ‘n’ cream", "National Peaches ‘n’ Cream Day", "the US"],
	[6, 25, "catfish", "National Catfish Day", "the US"],
	[6, 26, "chocolate pudding", "National Chocolate Pudding Day", "the US"],
	[6, 27, "orange blossom", "National Orange Blossom Day", "the US"],
	[6, 28, "ceviche", "National Ceviche Day", "the US"],
	[6, 28, "bowl of tapioca", "National Tapioca Day", "the US"],
	[7, 1, "strange flavor of ice cream", "National Creative Ice Cream Flavor Day", "the US"],
	[7, 1, "gingersnap", "National Gingersnap Day", "the US"],
	[7, 2, "anisette", "National Anisette Day", "the US"],
	[7, 3, "can of beans", "Eat Beans Day", "the US"],
	[7, 3, "chocolate wafer", "National Chocolate Wafer Day", "the US"],
	[7, 4, "Caesar salad", "National Caesar Salad Day", "the US"],
	[7, 4, "rack of spare ribs", "National Spareribs Day", "the US"],
	[7, 4, "BBQ", "National Barbecue Day", "the US"],
	[7, 5, "apple turnover", "National Apple Turnover Day", "the US"],
	[7, 6, "whatever your webmaster wants", "Take Your Webmaster to Lunch Day (P.S., he wants burritos!)", "the US"],
	[7, 6, "fried chicken", "National Fried Chicken Day", "the US"],
	[7, 7, "mac & cheese", "Macaroni Day", "the US"],
	[7, 7, "strawberry sundae", "National Strawberry Sundae Day", "the US"],
	[7, 8, "chocolate bar with almonds", "National Chocolate with Almonds Day", "the US"],
	[7, 9, "sugar cookie", "National Sugar Cookie Day", "the US"],
	[7, 10, "piña colada", "National Piña Colada Day", "the US"],
	[7, 11, "blueberry muffin", "National Blueberry Muffin Day", "the US"],
	[7, 12, "pecan pie", "National Pecan Pie Day", "the US"],
	[7, 13, "bunch of french fries", "National French Fries Day", "the US"],
	[7, 13, "BBQ", "National BBQ Day", "the US"],
	[7, 14, "grand marnier", "National Grand Marnier Day", "the US"],
	[7, 14, "mac & cheese", "National Mac & Cheese Day", "the US"],
	[7, 15, "tapioca pudding", "National Tapioca Pudding Day", "the US"],
	[7, 15, "gummi worm", "Gummi Worm Day", "the US"],
	[7, 16, "spinach salad", "Fresh Spinach Day", "the US"],
	[7, 16, "corn fritter", "National Corn Fritter Day", "the US"],
	[7, 17, "peach ice cream", "National Peach Ice Cream Day", "the US"],
	[7, 18, "caviar", "National Caviar Day", "the US"],
	[7, 19, "daiquiri", "National Daiquiri Day", "the US"],
	[7, 20, "fortune cookie", "National Fortune Cookie Day", "the US"],
	[7, 20, "lollipop", "National Lollipop Day", "the US"],
	[7, 21, "fast food burger", "National Junk Food Day", "the US"],
	[7, 22, "penuche fudge", "National Penuche Fudge Day", "the US"],
	[7, 23, "vanilla ice cream cone", "National Vanilla Ice Cream Day", "the US"],
	[7, 23, "hot dog", "National Hot Dog Day", "the US"],
	[7, 24, "shot of tequila", "National Tequila Day", "the US"],
	[7, 24, "Sonic burger", "National Drive-Thru Day", "the US"],
	[7, 25, "hot fudge sundae", "National Hot Fudge Sundae Day", "the US"],
	[7, 26, "coffee milkshake", "National Coffee Milkshake Day", "the US"],
	[7, 27, "creme brulee", "National Creme Brulee Day", "the US"],
	[7, 27, "glass of Scotch whisky", "National Scotch Day", "the US"],
	[7, 28, "hamburger", "Hamburger Day", "the US"],
	[7, 28, "milk chocolate", "National Milk Chocolate Day", "the US"],
	[7, 29, "lasagna", "National Lasagna Day", "the US"],
	[7, 29, "chicken wing", "National Chicken Wing Day", "the US"],
	[7, 30, "cheesecake", "National Cheesecake Day", "the US"],
	[7, 31, "raspberry cake", "National Raspberry Cake Day", "the US"],
	[8, 1, "milkshake", "National Milkshake Day", "the US"],
	[8, 3, "watermelon", "National Watermelon Day", "the US"],
	[8, 3, "glass of chardonnay", "National White Wine Day", "the US"],
	[8, 10, "s’more", "National S’more Day", "the US"],
	[8, 13, "filet mignon", "National Filet Mignon Day", "the US"],
	[8, 14, "creamsicle", "National Creamsicle Day", "the US"],
	[8, 15, "lemon merignue pie", "National Lemon Meringue Pie Day", "the US"],
	[8, 16, "Hotel Nacional", "National Rum Day", "the US"],
	[8, 16, "bratwurst", "World Bratwurst Day", "the US"],
	[8, 17, "vanilla custard", "National Vanilla Custard Day", "the US"],
	[8, 18, "glass of pinot noir", "National Pinot Noir Day", "the US"],
	[8, 19, "potato", "National Potato Day", "the US"],
	[8, 21, "spumoni", "National Spumoni Day", "the US"],
	[8, 22, "pecan torte", "National Pecan Torte Day", "the US"],
	[8, 22, "peach", "National Eat A Peach Day", "the US"],
	[8, 23, "sponge cake", "National Sponge Cake Day", "the US"],
	[8, 24, "peach pie", "National Peach Pie Day", "the US"],
	[8, 24, "waffle", "National Waffle Day", "the US"],
	[8, 25, "banana split", "National Banana Split Day", "the US"],
	[8, 25, "whiskey sour", "National Whiskey Sour Day", "the US"],
	[8, 26, "cherry popsicle", "National Cherry Popsicle Day", "the US"],
	[8, 27, "pot de creme", "National Pots De Creme Day", "the US"],
	[8, 27, "banana", "National Banana Lovers Day", "the US"],
	[8, 28, "cherry turnover", "National Cherry Turnover Day", "the US"],
	[8, 28, "cracker over your keyboard", "Crackers Over The Keyboard Day", "the US"],
	[8, 29, "parsley, sage, rosemary and thyme", "More Herbs, Less Salt Day", "the US"],
	[8, 29, "squeezed lemon", "National Lemon Juice Day", "the US"],
	[8, 29, "chop suey", "National Chop Suey Day", "the US"],
	[8, 30, "toasted marshmallow", "National Toasted Marshmallow Day", "the US"],
	[8, 31, "trail mix", "Trail Mix Day", "the US"],
	[9, 1, "cherry popover", "National Cherry Popover Day", "the US"],
	[9, 2, "blueberry popsicle", "National Blueberry Popsicle Day", "the US"],
	[9, 3, "Welsh rarebit", "National Welsh Rarebit Day", "the US"],
	[9, 4, "macademia nut", "National Macademia Nut Day", "the US"],
	[9, 5, "cheese pizza", "National Cheese Pizza Day", "the US"],
	[9, 6, "coffee ice cream", "National Coffee Ice Cream Day", "the US"],
	[9, 7, "glass of beer", "National Beer Lover’s Day", "the US"],
	[9, 7, "acorn squash", "National Acorn Squash Day", "the US"],
	[9, 7, "salami", "National Salami Day", "the US"],
	[9, 9, "wienerschnitzel", "Wienerschnitzel Day", "the US"],
	[9, 9, "steak au poivre", "National Steak Au Poivre Day", "the US"],
	[9, 10, "TV dinner", "National TV Dinner Day", "the US"],
	[9, 11, "hot cross bun", "National Hot Cross Bun Day", "the US"],
	[9, 12, "chocolate milkshake", "National Chocolate Milkshake Day", "the US"],
	[9, 13, "peanut", "National Peanut Day", "the US"],
	[9, 13, "chocolate bar", "International Chocolate Day", "the US"],
	[9, 14, "hoagie", "National Eat a Hoagie Day", "the US"],
	[9, 14, "cream-filled donut", "National Cream Filled Donut Day", "the US"],
	[9, 15, "Grasshopper (the drink, not the insect)", "National Crème de Menthe Day", "the US"],
	[9, 15, "double cheeseburger", "National Double Cheeseburger Day", "the US"],
	[9, 15, "linguine", "National Linguine Day", "the US"],
	[9, 15, "cheese toast", "National Cheese Toast Day", "the US"],
	[9, 16, "guacamole", "National Guacamole Day", "the US"],
	[9, 16, "cinnamon-raisin bread", "National Cinnamon-Raisin Bread Day", "the US"],
	[9, 17, "apple dumpling", "National Apple Dumpling Day", "the US"],
	[9, 17, "Monte Cristo sandwich", "National Monte Cristo sandwich Day", "the US"],
	[9, 18, "cheeseburger", "National Cheeseburger Day", "the US"],
	[9, 19, "butterscotch pudding", "National Butterscotch Pudding Day", "the US"],
	[9, 20, "pepperoni pizza", "National Pepperoni Pizza Day", "the US"],
	[9, 20, "glass of punch", "National Punch Day", "the US"],
	[9, 20, "glass of rum punch", "National Rum Punch Day", "the US"],
	[9, 21, "pecan cookie", "National Pecan Cookie Day", "the US"],
	[9, 25, "lobster", "National Lobster Day", "the US"],
	[9, 26, "healthy breakfast", "National Better Breakfast Day", "the US"],
	[9, 26, "pancake", "National Pancake Day", "the US"],
	[9, 26, "dumpling", "National Dumpling Day", "the US"],
	[9, 26, "apple", "Johnny Appleseed Day", "the US"],
	[9, 27, "chocolate milk", "National Chocolate Milk Day", "the US"],
	[9, 27, "corned beef hash", "National Corned Beef Hash Day", "the US"],
	[9, 28, "meal with your children for once you terrible parent", "Family Day – A Day to Eat Dinner with Your Children", "the US"],
	[9, 28, "strawberry cream pie", "National Strawberry Cream Pie Day", "the US"],
	[9, 28, "glass of beer", "National Drink Beer Day", "the US"],
	[9, 29, "cup of coffee", "National Coffee Day", "the US"],
	[9, 29, "biscotti", "National Biscotti Day", "the US"],
	[9, 30, "hot mulled cider", "National Hot Mulled Cider Day", "the US"],
	[10, 4, "shot of vodka", "National Vodka Day", "the US"],
	[10, 4, "taco", "National Taco Day", "the US"],
	[10, 6, "bowl of noodles", "National Noodle Day", "the US"],
	[10, 11, "sausage pizza", "National Sausage Pizza Day", "the US"],
	[10, 14, "dessert for dinner", "National Dessert Day", "the US"],
	[10, 18, "chocolate cupcake", "National Chocolate Cupcake Day", "the US"],
	[10, 20, "brandied fruit", "National Brandied Fruit Day", "the US"],
	[10, 23, "Boston creme pie", "National Boston Creme Pie Day", "the US"],
	[10, 24, "bologna sandwich", "National Bologna Day", "the US"],
	[10, 24, "meal of some kind", "National Food Day", "the US"],
	[10, 25, "greasy meal", "National Greasy Food Day", "the US"],
	[10, 28, "chocolate bar", "National Chocolate Day", "the US"],
	[10, 29, "bowl of oatmeal", "National Oatmeal Day", "the US"],
	[10, 30, "whatever’s in the back of your fridge", "Haunted Refrigerator Night", "the US"],
	[10, 30, "candy corn", "National Candy Corn Day", "the US"],
	[10, 31, "candy apple", "National Candy Apple Day", "the US"],
	[10, 31, "caramel apple", "National Caramel Apple Day", "the US"],
	[11, 1, "shot of vinegar, I guess?", "National Vinegar Day", "the US"],
	[11, 1, "french-fried clam", "National French Fried Clam Day", "the US"],
	[11, 2, "deviled egg", "National Deviled Egg Day", "the US"],
	[11, 3, "sandwich", "National Sandwich Day", "the US"],
	[11, 4, "candy", "National Candy Day", "the US"],
	[11, 4, "healthy meal", "National Eating Healthy Day", "the US"],
	[11, 5, "doughnut", "National Doughnut Day", "the US"],
	[11, 6, "plate of nachos", "National Nachos Day", "the US"],
	[11, 7, "bittersweet chocolate with almonds", "National Bittersweet Chocolate with Almonds Day", "the US"],
	[11, 8, "Harvey Wallbanger", "National Harvey Wallbanger Day", "the US"],
	[11, 8, "fragrant curry", "Cook Something Bold and Pungent Day", "the US"],
	[11, 8, "cappucino", "National Cappuccino Day", "the US"],
	[11, 8, "tequila shot", "National Shot Day", "the US"],
	[11, 9, "scrapple", "National Scrapple Day", "the US"],
	[11, 10, "vanilla cupcake", "National Vanilla Cupcake Day", "the US"],
	[11, 11, "sundae", "National Sundae Day", "the US"],
	[11, 12, "pizza with anything except anchovies", "National Pizza with the Works Except Anchovies Day", "the US"],
	[11, 12, "book? I guess?", "Chicken Soup for the Soul Day", "the US"],
	[11, 12, "cheap glass of beer", "National Happy Hour Day", "the US"],
	[11, 13, "bowl of Indian pudding", "National Indian Pudding Day", "the US"],
	[11, 14, "pickle", "National Pickle Day", "the US"],
	[11, 14, "spicy guacamole", "National Spicy Guacamole Day", "the US"],
	[11, 15, "spicy hermit cookie", "National Spicy Hermit Cookie Day", "the US"],
	[11, 15, "whatever’s in your fridge", "National Clean Out Your Refrigerator Day", "the US"],
	[11, 16, "fast food meal", "National Fast Food Day", "the US"],
	[11, 17, "baklava", "National Baklava Day", "the US"],
	[11, 17, "slice of homemade bread", "Homemade Bread Day", "the US"],
	[11, 18, "bowl of vichyssoise", "National Vichyssoise Day", "the US"],
	[11, 18, "apple cider", "National Apple Cider Day", "the US"],
	[11, 19, "Barq’s Root Beer", "Carbonated Beverage with Caffeine Day", "the US"],
	[11, 20, "peanut butter fudge bar", "National Peanut Butter Fudge Day", "the US"],
	[11, 21, "bowl of stuffing", "National Stuffing Day", "the US"],
	[11, 22, "cranberry relish", "National Cranberry Relish Day", "the US"],
	[11, 23, "cashew", "National Cashew Day", "the US"],
	[11, 23, "cranberry", "National Eat A Cranberry Day", "the US"],
	[11, 24, "espresso", "National Espresso Day", "the US"],
	[11, 25, "parfait", "National Parfait Day", "the US"],
	[11, 26, "cake", "National Cake Day", "the US"],
	[11, 27, "Bavarian cream pie", "National Bavarian Cream Pie Day", "the US"],
	[11, 28, "French toast", "National French Toast Day", "the US"],
	[11, 29, "anything but your leftovers; throw that shit out", "Throw Out Your Leftovers Day", "the US"],
	[11, 29, "lemon cream pie", "National Lemon Cream Pie Day", "the US"],
	[11, 29, "chocolate bar", "National Chocolates Day", "the US"],
	[11, 30, "mousse", "National Mousse Day", "the US"],
	[12, 1, "red apple", "Eat a Red Apple Day", "the US"],
	[12, 1, "pie", "National Pie Day", "the US"],
	[12, 2, "fritter", "National Fritters Day", "the US"],
	[12, 4, "cookie", "National Cookie Day", "the US"],
	[12, 5, "rock candy", "National Rock Candy Day", "the US"],
	[12, 8, "brownie", "National Brownie Day", "the US"],
	[12, 10, "lager", "National Lager Day", "the US"],
	[12, 11, "noodle ring", "National Noodle Ring Day", "the US"],
	[12, 11, "bagel", "National Have A Bagel Day", "the US"],
	[12, 13, "ice cream", "National Ice Cream Day", "the US"],
	[12, 15, "cupcake", "National Cupcake Day", "the US"],
	[12, 16, "anything chocolate-covered", "National Chocolate-Covered Anything Day", "the US"],
	[12, 17, "bottle of maple syrup", "National Maple Syrup Day", "the US"],
	[12, 20, "sangria", "National Sangria Day", "the US"],
	[12, 21, "burger", "National Hamburger Day", "the US"],
	[12, 22, "slice of date nut bread", "National Date Nut Bread Day", "the US"],
	[12, 24, "egg nog", "National Eggnog Day", "the US"],
	[12, 25, "pumpkin pie", "National Pumpkin Pie Day", "the US"],
	[12, 27, "fruitcake", "National Fruitcake Day", "the US"],
	[12, 30, "spoonful of baking soda", "National Bicarbonate of Soda Day", "the US"],
	[12, 31, "glass of champagne", "National Champagne Day", "the US"]
];

monthDays = [ // month, day of week, occurrence in month
  [8, 5, 1, "glass of beer", "International Beer Day"],
  [10, 4, 2, "chicken", "World Chicken Day"],
  [10, 5, 2, "egg", "World Egg Day"],
  [2, 6, 1, "ice cream for breakfast", "Ice Cream for Breakfast Day", "the US"],
  [2, 1, 1, "fro-yo", "National Frozen Yogurt Day", "the US"],
  [5, 5, 3, "pizza", "National Pizza Party Day", "the US"],
  [6, 5, 1, "doughnut", "National Doughnut Day", "the US"],
  [7, 0, 3, "ice cream", "National Ice Cream Day", "the US"],
  [7, 4, 4, "chili dog", "National Chili Dog Day", "the US"],
  [8, 6, 1, "bowl of mustard", "National Mustard Day", "the US"],
  [11, 4, 1, "dinner cooked by a man", "National Men Make Dinner Day", "the US"],
  [11, 4, 1, "stout beer", "International Stout Day", "the US"],
  [11, 4, 4, "turkey", "Thanksgiving", "the US"]
]

ranges = [ // month, day, month, day
  [2, 5, 2, 11, "healthy amount of food", "Eating Disorders Awareness Week", "Canada"],
  [8, 5, 8, 11, "meal from a farmers market", "Farmers Market Week", "the US"],
  [10, 14, 10, 20, "school lunch", "National School Lunch Week", "the US"],
  [1, 2, 1, 9, "buffet", "National Buffet Week", "the US"]
]

monthWeeks = [ // month, week #
  [6, 1, "fro-yo", "Frozen Yogurt Week", "the US"],
  [7, 4, "salad", "Salad Week", "the US"],
  [9, 1, "vegetarian meal", "Vegetarian Awareness Week", "the US"],
  [9, 2, "waffle", "National Waffle Week", "the US"],
  [10, 1, "hospital meal", "National Health Care Food Service Week", "the US"],
  [10, 1, "low-sodium meal", "No Salt Week", "the US"],
  [11, 1, "fig", "National Fig Week", "the US"],
  [11, 2, "split-pea soup", "National Split Pea Soup Week", "the US"]
];

months = [
  [3, "nutitious meal", "National Nutrition Month", "Canada"],
  [5, "meal that you’re allergic to", "Food Allergy Awareness Month", "Canada"],
  [1, "meal out", "Be Kind to Food Servers Month", "Tennessee"],
  [1, "dried plum", "Dried Plum Digestive Health Month", "California"],
  [1, "cup of hot tea", "Hot Tea Month", "the US"],
  [1, "cup of soup", "National Soup Month", "the US"],
  [1, "bowl of oatmeal", "Oatmeal Month", "the US"],
  [2, "birdfeed", "National Bird-Feeding Month", "the US"],
  [3, "celery", "National Celery Month", "the US"],
  [3, "frozen TV dinner", "National Frozen Food Month", "the US"],
  [3, "peanut", "National Peanut Month", "the US"],
  [4, "fresh Florida tomato", "Fresh Florida Tomato Month", "the US"],
  [4, "anything I guess", "National Food Month", "the US"],
  [4, "grilled cheese sandwich", "National Grilled Cheese Month", "the US"],
  [4, "pecan", "National Pecan Month", "the US"],
  [4, "soft pretzel", "National Soft Pretzel Month", "the US"],
  [4, "soy-based meat substitute", "National Soyfoods Month", "the US"],
  [5, "strawberry", "National Strawberry Month", "the US"],
  [6, "cheesy thing", "Dairy Month", "the US"],
  [6, "fake cheesy thing", "Dairy Alternatives Month", "the US"],
  [6, "candy bar", "National Candy Month", "the US"],
  [6, "fro-yo", "National Frozen Yogurt Month", "the US"],
  [6, "fruit and vegetable platter", "National Fruit and Vegetables Month", "the US"],
  [6, "ice tea", "National Ice Tea Month", "the US"],
  [6, "K-rab", "National Surimi Seafood Month", "the US"],
  [6, "turkey", "National Turkey Lovers’ Month", "the US"],
  [6, "bottle of wine", "Wine Month", "Ohio"],
  [7, "berry", "Berry Month", "the US"],
  [7, "blueberry", "Blueberry Month", "the US"],
  [7, "California wild king salmon", "California Wild King Salmon Month", "the US"],
  [7, "fancy meal", "Culinary Arts Month", "the US"],
  [7, "grilled steak", "Grilling Month", "the US"],
  [7, "horseradish", "Horseradish Month", "the US"],
  [7, "ice cream cone", "National Ice Cream Month ", "the US"],
  [7, "picnic", "Picnic Month", "the US"],
  [8, "catfish", "Catfish Month", "the US"],
  [8, "dinner with your family", "Family Meals Month", "the US"],
  [8, "kiwi", "Get Acquainted with Kiwifruit Month", "the US"],
  [8, "TV dinner alone", "Sad TV Dinners For One Month", "the US"],
  [8, "Dippin’ Dots", "National Dippin’ Dots Month", "the US"],
  [8, "peach", "Peach Month", "the US"],
  [8, "sandwich", "Sandwich Month", "the US"],
  [9, "bottle of bourbon", "National Bourbon Heritage Month", "the US"],
  [9, "healthier breakfast", "Better Breakfast Month", "the US"],
  [9, "Napa Valley wine", "California Wine Month", "the US"],
  [9, "fully-cooked chicken", "Food Safety Education Month", "the US"],
  [9, "chicken", "National Chicken Month", "the US"],
  [9, "anything other than McDonald’s", "National Childhood Obesity Awareness Month", "the US"],
  [9, "jar of honey", "National Honey Month", "the US"],
  [9, "mushroom", "National Mushroom Month", "the US"],
  [9, "papaya", "National Papaya Month", "the US"],
  [9, "potato", "National Potato Month", "the US"],
  [9, "bowl of rice", "National Rice Month", "the US"],
  [9, "wheat bread", "National Whole Grains Month", "the US"],
  [9, "wild rice", "National Wild Rice Month", "the US"],
  [10, "apple", "Apple Month", "the US"],
  [10, "sun-dried tomato", "Celebrate Sun Dried Tomatoes Month", "the US"],
  [10, "cranberry", "Cranberry Month", "the US"],
  [10, "healthy meal with some friends", "Eat Better, Eat Together Month", "the US"],
  [10, "fresh fruit and vegetable meal at your school", "Farm to School Month", "the US"],
  [10, "country ham", "Go Hog Wild—Eat Country Ham Month", "the US"],
  [10, "lot of candy bars and no syringes or razors", "Halloween Safety Month", "the US"],
  [10, "bowl of chili", "National Chili Month", "the US"],
  [10, "cookie", "National Cookie Month", "the US"],
  [10, "pizza", "National Pizza Month", "the US"],
  [10, "seafood salad", "National Seafood Month", "the US"],
  [10, "pasta salad", "Pasta Month", "the US"],
  [10, "bowl of popcorn", "National Popcorn Poppin’ Month", "the US"],
  [10, "roast porkchop", "Pork Month", "the US"],
  [10, "spinach salad", "Spinach Lovers Month", "the US"],
  [10, "vegetarian meal", "Vegetarian Awareness Month", "the US"],
  [10, "Virginia wine", "Virginia Wine Month", "the US"],
  [11, "PB&J", "National Peanut Butter Lovers Month", "the US"],
  [11, "sweet potato", "Sweet Potato Awareness Month", "the US"],
  [12, "egg nog", "National Egg Nog Month", "the US"],
  [12, "fruitcake", "National Fruit Cake Month", "the US"],
  [12, "pear", "National Pear Month", "the US"]
];

function holidaysToday() {
  var holidaysToday = [];
  today = moment().startOf('day');
  
  for (var i=0; i!=days.length; i++) {
    var testDay = moment().startOf('year').month(days[i][0] - 1).date(days[i][1]);
    if (today.isSame(testDay)) {
      holidaysToday.push([days[i][2], days[i][3], days[i][4]]);
    }
  }
  
  for (var i=0; i!=monthDays.length; i++) {
    var firstDayOfMonth = moment().startOf('year').month(monthDays[i][0] - 1);
    var testDay;
    if (monthDays[i][1] >= firstDayOfMonth.day()) {
      testDay = firstDayOfMonth.clone().day(monthDays[i][1]).add(monthDays[i][2]-1, 'weeks');
    } else {
      testDay = firstDayOfMonth.clone().day(monthDays[i][1] + 7).add(monthDays[i][2]-1, 'weeks');
    }
    if (today.isSame(testDay)) {
      holidaysToday.push([monthDays[i][3], monthDays[i][4], monthDays[i][5]]);
    }
  }
  
  for (var i=0; i!=ranges.length; i++) {
    var start = moment().startOf('year').month(ranges[i][0] - 1).date(ranges[i][1]);
    var end = moment().startOf('year').month(ranges[i][2] - 1).date(ranges[i][3]);
    if (today.isBetween(start, end)) {
      holidaysToday.push([ranges[i][4], ranges[i][5], ranges[i][6]]);
    }
  }
  
  for (var i=0; i!=monthWeeks.length; i++) {
    var start = moment().startOf('year').month(monthWeeks[i][0] - 1).add(monthWeeks[i][1] - 1, 'weeks');
    var end = start.clone().add(1, 'weeks');
    if (today.isBetween(start, end)) {
      holidaysToday.push([monthWeeks[i][2], monthWeeks[i][3], monthWeeks[i][4]]);
    }
  }
  
  for (var i=0; i!=months.length; i++) {
    if (today.month() == months[i][0] - 1) {
      holidaysToday.push([months[i][1], months[i][2], months[i][3]]);
    }
  }
  
  var shroveTuesday = moment.easter(moment().year()).subtract(47, 'days');
  if (today.isSame(shroveTuesday)) {
    holidaysToday.push(["pancake", "Shrove Tuesday"]);
  }
  
  var ashWednesday = moment.easter(moment().year()).subtract(7, 'weeks').day(3);
  if (today.isSame(ashWednesday.clone().subtract(8, 'days'))) {
    holidaysToday.push(["pancake", "National Pancake Day", "the Netherlands"]);
  }
  
  if (today.isSame(ashWednesday.clone().day(0+7).add(3, 'weeks'))) {
    holidaysToday.push(["pretzel", "Pretzel Sunday", "Luxembourg"]);
  }
  
  return holidaysToday;
}

function setHoliday() {
  var stuffToday = holidaysToday();
  var holiday = stuffToday[Math.floor(Math.random()*stuffToday.length)];
  
  $('h1').text(holiday[0]);
  var todayIs = "It’s " + holiday[1];
  if (holiday[2]) todayIs += " in " + holiday[2];
  todayIs += ".";
  
  $('#today-is').text(todayIs);
}

function setBackgroundColor() {
  var hue = Math.floor(Math.random()*360);
  $('body').css('background-color', 'hsl(' + hue + ', 30%, 70%)');
}

$(window).ready(function() {
  setHoliday();
  setBackgroundColor();
});